---
- hosts: masters
  become: true
  become_user: root
  tasks:
  - name: Deploy the Example Hello World
    command: "{{ item }}"
    with_items:
      - kubectl apply -f https://k8s.io/examples/service/access/hello-application.yaml
      - kubectl expose deployment hello-world --type=NodePort --name=example-service --port=80
    ignore_errors: yes
