
name: CI

on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29
        
      - name: Validate the Terraform code
        env:
          CLOUDSCALE_TOKEN: ${{ secrets.CLOUDSCALE_TOKEN }}
        run: |
          export CLOUDSCALE_TOKEN=$CLOUDSCALE_TOKEN
          cd terraform-infrastructure
          terraform init
          terraform plan -var-file=env/dev-environment.tfvars
          terraform apply -var-file=env/dev-environment.tfvars -auto-approve
          cd ../ansible-k8s
          ansible-playbook setup_master_node.yml
          ansible-playbook setup_worker_nodes.yml
          ansible-playbook deploy-hello-world.yml
          cd ../ansible-haproxy
          ansible-playbook deploy-haproxy.yml
          


      
          
