
name: CI

on:
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29
          host: ${{ secrets.SSH_KEY }}
        
      - name: Validate the Terraform code
        env:
          CLOUDSCALE_TOKEN: ${{ secrets.CLOUDSCALE_TOKEN }}
        run: |
          export CLOUDSCALE_TOKEN=$CLOUDSCALE_TOKEN
          cd terraform-infrastructure
          terraform init
          terraform plan -var-file=env/dev-environment.tfvars
          terraform apply -var-file=env/dev-environment.tfvars -auto-approve          

      - name: Run playbook Kubernetes Master
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: setup_master_node.yml
          directory: ansible-k8s
          key: ${{secrets.SSH_KEY}}
          
      
      - name: Run playbook Kubernetes Nodes
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: setup_worker_nodes.yml
          directory: ansible-k8s
          key: ${{secrets.SSH_KEY}}    

      - name: Run playbook Hello World
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-hello-world.yml
          directory: ansible-k8s
          key: ${{secrets.SSH_KEY}}   
        
      
      - name: Run playbook HAProxy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-haproxy.yml
          directory: ansible-haproxy
          key: ${{secrets.SSH_KEY}}  